
name: AWAF Sync

# Controls when the workflow will run
on:
  repository_dispatch:
    branches: [ "awaf-sync" ]
    types: [awaf-sync]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pull_waf_policy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Policy ID
        run: |
          POLICY_ID=`curl -sku ${F5_USER}:${F5_PASS} 'https://'${F5_MGMT_IP}'/mgmt/tm/asm/policies?$filter=name+eq+'"'"${POLICY_NAME}"'"'&$select=id' | jq -r '.items[].id'`
          echo "WAF Policy ID ${POLICY_ID}"
      - name: Start Export Policy Task
        run: |
          TASK_ID=`curl -sku ${F5_USER}:${F5_PASS} 'https://'${F5_MGMT_IP}'/mgmt/tm/asm/tasks/export-policy' -X POST -d '{"format":"json", "filename":"'${POLICY_NAME}'.json", "policyReference":{"link":"https://localhost/mgmt/tm/asm/policies/'${POLICY_ID}'"}, "minimal":true}' | jq -r '.id'`
          echo "Policy export task ID - ${TASK_ID}"
      - name: Check Export Policy Task Status
        run: |
          TASK_STATUS=`curl -sku ${F5_USER}:${F5_PASS} 'https://'${F5_MGMT_IP}'/mgmt/tm/asm/tasks/export-policy/'${TASK_ID} | jq -r '.status'`
          echo "Policy Export Task status is ${TASK_STATUS}"
      - name: Check Export Policy Task Status Until Complete
        run: |
          if [ $TASK_STATUS != "COMPLETED" ]
            then
              i=0
              while [ $i -le 10 ]
              do
                let i+=1
                echo "Policy Export Task status ${TASK_STATUS} != 'COMPLETED'. Retry ${i}/10 in 5 seconds......."
                sleep 5
                TASK_STATUS=`curl -sku ${F5_USER}:${F5_PASS} 'https://'${F5_MGMT_IP}'/mgmt/tm/asm/tasks/export-policy/'${TASK_ID} | jq -r '.status'`
                if [ $TASK_STATUS = "COMPLETED" ]
                then
                  echo "Policy Export Task status ${TASK_STATUS}."
                  break
                fi
              done
            else
              echo "Policy Export Task status ${TASK_STATUS}."
            fi
      - name: Download Policy
        run: curl -sku ${F5_USER}:${F5_PASS} 'https://'${F5_MGMT_IP}'/mgmt/tm/asm/file-transfer/downloads/'${POLICY_NAME}'.json' > ${F5_WAF_SYNC_BRANCH}/${POLICY_NAME}.json

